#!/bin/bash

# Make sure the user data directory is owned by the developer user
if [ -d /home/developer/.netbeans ]; then
  chown developer:developer /home/developer/.netbeans
fi
ls /usr/local/
exec /usr/local/netbeans-8.2/bin/netbeans
